name: flat_table
description: Flat Table Widget
version: 0.0.1
#repository: https://github.com/...
#issue_tracker: https://github.com/.../issues

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: '>=3.24.4'

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: any
  two_dimensional_scrollables: 0.3.4

  intl: any
  gap: any
  collection: any

  excel: 4.0.6
  file_saver: any
  responsive_grid_list: any
  decimal: any

dev_dependencies:
  ## lint
  dart_code_linter: 2.0.0
  flutter_lints: 5.0.0

topics:
  - table
  - widgets
