name: flat_table
description: Flat Table Widget
version: 0.0.1
#repository: https://github.com/...
#issue_tracker: https://github.com/.../issues

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.19.3'

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: any
  two_dimensional_scrollables: 0.2.1

  intl: any
  gap: any
  collection: any

  excel: 4.0.3
  file_saver: 0.2.12
  responsive_grid_list: any

dev_dependencies:
  ## lint
  dart_code_linter: 1.1.3
  flutter_lints: 3.0.2

topics:
  - table
  - widgets
